### ISSUE TITLE
Information request: *_SetpointHistory

### ISSUE THREAD

**Issue by DamianoP** [TechnicalBuildingSystems/OpenSmartHomeData#2]
Dear authors, what do the values called "*_SetpointHistory" represent ?
For example:
Room2_SetpointHistory

**Comment by GeorgFerdinandSchneider** [comment]
Dear @DamianoP ,

The setpoint history is a setpoint to the room temperature controller. Its generated by the smart home system based on the schedule of the controller and user preferences.

> SetpointHistory -> This is the setpoint for the room in degree Celsius as a floating point number as defined by the schedule of the controller.

As mentioned in the paper due to intellectual property reasons, we have not been able to include the actual control actions by the controller in our data.

We hope that explanation helps!

Best

Georg
